wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/deepseatreasure-pareto/agent.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1668712172.85543
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 23
      - 35
      4: 3.7.3
      5: 0.13.5
      8:
      - 3
      - 5
