wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/deepseatreasure-pareto/agent.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: global_step
    - 1: reward0
      5: 1
      6:
      - 1
    - 1: reward1
      5: 1
      6:
      - 1
    - 1: episode
      5: 1
      6:
      - 1
    - 1: paretoreward0
      5: 1
      6:
      - 1
    - 1: paretoreward1
      5: 1
      6:
      - 1
    - 1: paretoepisode
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table._type
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.sha256
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.size
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.artifact_path
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.path
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.ncols
      5: 1
      6:
      - 1
    - 1: my_custom_plot_id_table.nrows
      5: 1
      6:
      - 1
    python_version: 3.7.3
    start_time: 1668562428.43598
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      - 35
      4: 3.7.3
      5: 0.13.5
      8:
      - 3
      - 5
    visualize:
      my_custom_plot_id:
        panel_config:
          fieldSettings:
            x: x
            y: y
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: Custom Y vs X Scatter Plot
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_custom_plot_id_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
